image: 'rust:latest'

stages:
    - doc

pages:
    stage: doc
    only:
        - master
    script:
        - cargo doc --no-deps
        - rm -rf public
        - mv target/doc/ public
    artifacts:
        paths:
            - public
