image: 'rust:latest'

stages:
    - doc

pages:
    stage: doc
    only:
        - master
    script:
        - cargo doc --no-deps
        - rm -rf public
        - mv target/doc/ public
        - echo '<meta http-equiv="refresh" content="0; url=warp">' > public/index.html
    artifacts:
        paths:
            - public
