[package]
name = "warp"
version = "0.0.0"
description = "serve the web at warp speeds"
authors = ["Sean McArthur <sean@seanmonstar.com>"]
license = "MIT"

[dependencies]
base64 = "0.9.2"
bytes = "0.4.8"
crossbeam-channel = "0.1"
futures = "0.1"
http = "0.1"
hyper = "0.12.6"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5.2"
sha-1 = "0.7"
tokio = "0.1.7"
tungstenite = "0.5"

[dependencies.tokio-tungstenite]
default-features = false
git = "https://github.com/snapview/tokio-tungstenite"
features = ["tokio"]
#version = "0.5.1"

[dev-dependencies]
pretty_env_logger = "0.2"
serde_derive = "1.0"

[profile.release]
codegen-units = 1
incremental = false

[profile.bench]
codegen-units = 1
incremental = false
