[package]
name = "warp"
version = "0.0.0"
description = "serve the web at warp speeds"
authors = ["Sean McArthur <sean@seanmonstar.com>"]
license = "MIT"

[dependencies]
crossbeam-channel = "0.1"
futures = "0.1"
http = "0.1"
hyper = "0.12"
log = "0.4"
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
pretty_env_logger = "0.2"
serde_derive = "1.0"
